server:
  port: 8081

spring:
  application:
    name: client-consumer
  stream:
    bindings:
      myMessage:
         group: order
         content-type: application/json
  rabbitmq:
      host: 140.143.242.234
      port: 5672
      username: test
      password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

feign:
  hystrix:
    enabled: true
    ## 刷新时，关闭安全验证
   #management.security.enabled=false
management:
  security:
    enableled: true

