server:
  port: 8080

spring:
  application:
    name: config
    #注意rabbitMq的配置写得位置，在spring之下
  rabbitmq:
    host: 140.143.242.234
    port: 5672
    username: test
    password: 123456


  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/rmkdzdnpy/spring-cloud_config_center
          username: rmkdzdnpy
          password: rm82647826
          #本地存放从git上拉取的配置文件的位置
          basedir: G:\IdeaProjects\spring-cloud-mult\basedir



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"


